### ISSUE TITLE
Mobile gadgets Home

### ISSUE THREAD

**Issue by nkirusteph** [zuri-training/WF-PriceCompare-24#113]
created the mobile gadgets home and added pictures and labels

**Comment by Mayana74** [comment]
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=1951%3A18208

**Comment by Mayana74** [comment]
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=1951%3A18208
