### ISSUE TITLE
gadgets frame

### ISSUE THREAD

**Issue by nkirusteph** [zuri-training/WF-PriceCompare-24#130]
created and added necessary content to the gadgets frames

**Comment by olasb** [comment]
desktop gadgets frame
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=537%3A2012

**Comment by olasb** [comment]
desktop gadgets frame
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=537%3A2012
