### ISSUE TITLE
desktop compare pages and mobile compare pages

### ISSUE THREAD

**Issue by nkirusteph** [zuri-training/WF-PriceCompare-24#175]
created desktop and mobile compare pages

**Comment by olasb** [comment]
compare gadgets
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=1974%3A23745

**Comment by olasb** [comment]
compare fashion
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=1974%3A24019

**Comment by olasb** [comment]
desktop compare gadget
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=1974%3A23231

**Comment by olasb** [comment]
Desktop compare fashion
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=1972%3A22838
