### ISSUE TITLE
desktop landing page

### ISSUE THREAD

**Issue by nkirusteph** [zuri-training/WF-PriceCompare-24#180]
helped add content to desktop landing page along with mayana

**Comment by olasb** [comment]
w

**Comment by olasb** [comment]
worked on the desktop landing page both hi-fi andlo-fi
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=530%3A2028

**Comment by olasb** [comment]
worked on the desktop landing page both hi-fi andlo-fi
https://www.figma.com/file/LEKdq0JqyuzzOGxv0tZWjh/WalletFriendly?node-id=530%3A2028
